config/routes.rb
Book2Drink::Application.routes.draw do
  
  devise_for :users, :controllers => { :sessions => "devise/sessions",
                                       :omniauth_callbacks => "users/omniauth_callbacks" ,
                                       :registrations => "registration"
                                     }
  resources :users do
    resources :commentbooks
    resources :user_libraries
  end
  
  resources :events
  resources :user_libraries do
    collection do
      get 'public_userlibrary/:id', :action => 'public_userlibrary', :as => 'public_userlibrary'
    end
  end
  resources :city_types do
    resources :locations
  end
  resources :commentlocations
  resources :locations do
    resources :commentlocations
    resources :events
  end
  
  resources :commentbooks
  resources :isbninfos do 
    resources :commentbooks
    resources :user_libraries
    collection do
      get 'indexsearchbooks'
      post 'addtobooks'
    end
  end
  match "aftersignin_step1" => "registrati"

  get "admin/users"
  get "admin/locations"
  get "admin/isbninfos"
  get "admin/console"
  get "main/index"

  match "tour" => "main#tour"

  root :to => 'main#index'

end

app/controllers/city_types_controller.rb
class CityTypesController < ApplicationController
  protect_from_forgery
  before_filter :verify_admin
  
  # GET /city_types
  # GET /city_types.json
  def index
    @city_types = CityType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @city_types }
    end
  end

  # GET /city_types/1
  # GET /city_types/1.json
  def show
    @city_type = CityType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city_type }
    end
  end

  # GET /city_types/new
  # GET /city_types/new.json
  def new
    @city_type = CityType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @city_type }
    end
  end

  # GET /city_types/1/edit
  def edit
    @city_type = CityType.find(params[:id])
  end

  # POST /city_types
  # POST /city_types.json
  def create
    @city_type = CityType.new(params[:city_type])

    respond_to do |format|
      if @city_type.save
        format.html { redirect_to @city_type, notice: 'City type was successfully created.' }
        format.json { render json: @city_type, status: :created, location: @city_type }
      else
        format.html { render action: "new" }
        format.json { render json: @city_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /city_types/1
  # PUT /city_types/1.json
  def update
    @city_type = CityType.find(params[:id])

    respond_to do |format|
      if @city_type.update_attributes(params[:city_type])
        format.html { redirect_to @city_type, notice: 'City type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @city_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /city_types/1
  # DELETE /city_types/1.json
  def destroy
    @city_type = CityType.find(params[:id])
    @city_type.destroy

    respond_to do |format|
      format.html { redirect_to city_types_url }
      format.json { head :ok }
    end
  end
end

app/helpers/city_types_helper.rb
module CityTypesHelper
end

app/views/city_types/_form.html.erb
<%= form_for(@city_type) do |f| %>
  <% if @city_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city_type.errors.count, "error") %> prohibited this city_type from being saved:</h2>

      <ul>
      <% @city_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">Nombre de la ciudad:  <%= text_field(:city_type, :name, :class => 'round') %></div>
	<div class="field">País de la ciudad:  FIJO_ESPAÑA</div>
	

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/city_types/edit.html.erb
<h1>Editing city_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @city_type %> |
<%= link_to 'Back', city_types_path %>

app/views/city_types/index.html.erb
<h1>Listing city_types</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @city_types.each do |city_type| %>
  <tr>
    <td>Ciudad: <%= city_type.name %>		<td><%= link_to 'Show', city_type %>
    <%= link_to 'Edit', edit_city_type_path(city_type) %>
    <%= link_to 'Destroy', city_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New City type', new_city_type_path %>

app/views/city_types/new.html.erb
<h1>New city_type</h1>

<%= render 'form' %>

<%= link_to 'Back', city_types_path %>

app/views/city_types/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_city_type_path(@city_type) %> |
<%= link_to 'Back', city_types_path %>