config/routes.rb
Book2Drink::Application.routes.draw do
  
  devise_for :users, :controllers => { :sessions => "devise/sessions",
                                       :omniauth_callbacks => "users/omniauth_callbacks" ,
                                       :registrations => "registration"
                                     }
  resources :users do
    resources :commentbooks
    resources :user_libraries
  end
  
  resources :events
  resources :user_libraries do
    collection do
      get 'public_userlibrary/:id', :action => 'public_userlibrary', :as => 'public_userlibrary'
    end
  end
  resources :city_types do
    resources :locations
  end
  resources :commentlocations
  resources :locations do
    resources :commentlocations
    resources :events
  end
  
  resources :commentbooks
  resources :isbninfos do 
    resources :commentbooks
    resources :user_libraries
    collection do
      get 'indexsearchbooks'
      post 'addtobooks'
    end
  end
  match "aftersignin_step1" => "registrati"

  get "admin/users"
  get "admin/locations"
  get "admin/isbninfos"
  get "admin/console"
  get "main/index"

  match "tour" => "main#tour"

  root :to => 'main#index'

end

app/views/admin/console.html.erb
<div class="divBorder">
  <span>Consola de administración de Book2Drink</span>
  <ul>
    <li><%= link_to "Administración usuarios", admin_users_url %> </li>
    <li><%= link_to "Administración locales", admin_locations_url %> </li>
    <li><%= link_to "Administración libros", admin_isbninfos_url %> </li>
  </ul>
</div>

app/views/admin/isbninfos.html.erb
<div class="divBorder">

  <% @isbninfos.each do |isbninfo| %>
    <div class="libroAdmin" style="width: auto;">
      <%= link_to isbninfo.title, isbninfo %> de: <%= isbninfo.author %>
      ISBN: <%= isbninfo.isbn13 %>
    </div>
  <% end %>
</div>

app/views/admin/locations.html.erb
<div class="templatemo_box">
  <h2><span></span>Lista de bares de tu ciudad</h2>
  <div class="body">
    <table>
      <tr>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @locations.each do |location| %>
        <tr>

          <td><h4><%= link_to location.name, location %></h4></td>

        </tr>
      <% end %>
    </table>

  </div>
  <div class="box_bottom"><span></span></div>
</div>

app/views/admin/users.html.erb
<div class="templatemo_box">
  <h2><span></span>Listado de usuarios</h2>
  <div class="body">


    <table border="1">
      <tr>
        <th>Id</th>
        <th>Usuario</th>
        <th>Nombre</th>
        <th>Email</th>
        <th>Ciudad</th>
        <th>Bar</th>
        <th></th>
      </tr>

      <% @users.each do |user| %>
        <tr>
          <td><%=user.id%></td>
          <td><%=user.username%></td>
          <td><%=user.name %> <%=user.surname%></td>
          <td><%=user.email%></td>

          <% @city_type = CityType.find(1) %>
          <td>
            <%
            if user.city_type_id
              @city = CityType.find(user.city_type_id)
            %>
              <%= @city.name %> (<%=user.city_type_id%>)
            <% end %>
          </td>
          <td>
            <%
            if user.locations_id
              @location = Location.find(user.locations_id)
            %>
              <%= @location.name %> (<%= @location.id %>)
            <% end %>
          </td>
          <td> <%= link_to 'Show', user %> <%= link_to 'Edit', edit_user_path(user) %> <%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
      <% end %>
    </table>

    <br />

    <%= link_to 'New User', new_user_path %>



  </div>
  <div class="box_bottom"><span></span></div>
</div>