config/routes.rb
Book2Drink::Application.routes.draw do
  
  devise_for :users, :controllers => { :sessions => "devise/sessions",
                                       :omniauth_callbacks => "users/omniauth_callbacks" ,
                                       :registrations => "registration"
                                     }
  resources :users do
    resources :commentbooks
    resources :user_libraries
  end
  
  resources :events
  resources :user_libraries do
    collection do
      get 'public_userlibrary/:id', :action => 'public_userlibrary', :as => 'public_userlibrary'
    end
  end
  resources :city_types do
    resources :locations
  end
  resources :commentlocations
  resources :locations do
    resources :commentlocations
    resources :events
  end
  
  resources :commentbooks
  resources :isbninfos do 
    resources :commentbooks
    resources :user_libraries
    collection do
      get 'indexsearchbooks'
      post 'addtobooks'
    end
  end
  match "aftersignin_step1" => "registrati"

  get "admin/users"
  get "admin/locations"
  get "admin/isbninfos"
  get "admin/console"
  get "main/index"

  match "tour" => "main#tour"

  root :to => 'main#index'

end

app/models/user_library.rb
class UserLibrary < ActiveRecord::Base
  
    belongs_to :isbninfo
  belongs_to :user
  belongs_to :reading_status_book

end

app/controllers/user_libraries_controller.rb
class UserLibrariesController < ApplicationController
  include UserLibrariesHelper
  protect_from_forgery
  before_filter :verify_admin, :only => [:show, :new, :edit]

  # GET /user_libraries
  # GET /user_libraries.json
  def index
    @mode = params[:mode]
    if @mode == 'favorites' 
      @user_libraries = user_library.where(:favorite => true)
    elsif @mode == 'wished'
      @user_libraries = user_library.where(:wished => true)
    else 
      @user_libraries = user_library.all
    end

    @user_libraries = Kaminari.paginate_array(@user_libraries)
              .page(params[:page])
              .per(Book2Drink::Application.config.resultsperpage)

    @totalUserLibrary = current_user.user_libraries.length
    #user_library_by_id(@user.id).length

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_libraries }
    end
  end

  #este método obtiene la librería del usuario pasado por parámetro
  def public_userlibrary
    @mode = params[:mode]
    @user = User.find(params[:id])
    @totalUserLibrary = user_library_by_id(@user.id).length
    if @mode == 'favorites'
      @user_libraries = user_library_by_id(@user.id).where(:favorite => true)
    elsif @mode == 'wished'
      @user_libraries = user_library_by_id(@user.id).where(:wished => true)
    else
      @user_libraries = user_library_by_id(@user.id).all
    end

    @user_libraries = Kaminari.paginate_array(@user_libraries)
              .page(params[:page])
              .per(Book2Drink::Application.config.resultsperpage)

  end

  # GET /user_libraries/1
  # GET /user_libraries/1.json
  def show
    @user_library = UserLibrary.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_library }
    end
  end

  # GET /user_libraries/new
  # GET /user_libraries/new.json
  def new
    @user_library = UserLibrary.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_library }
    end
  end

  # GET /user_libraries/1/edit
  def edit
    @user_library = UserLibrary.find(params[:id])
  end

  # POST /user_libraries
  # POST /user_libraries.json
  def create
    @user_library = UserLibrary.new(params[:user_library])
     #se pone por defecto el estado de libro: "por leer"
    @user_library.isbninfo_id = params[:user_library][:isbninfo_id]
    @user_library.user_id = params[:user_library][:user_id]
    @user_library.reading_status_book_id = 1
    
    respond_to do |format|

      @user_library = save_userlibrary_check_repetition(@user_library)
      if (@user_library != nil)
        format.html { redirect_to :controller => "user_libraries", :action => "index", notice: 'User library was successfully created.'}

        #format.html { redirect_to @user_library, notice: 'User library was successfully created.' }
        #format.json { render json: @user_library, status: :created, location: @user_library }
      else
        format.html { render action: "new" }
        format.json { render json: @user_library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_libraries/1
  # PUT /user_libraries/1.json
  def update
    @user_library = UserLibrary.find(params[:id])

    respond_to do |format|
      if @user_library.update_attributes(params[:user_library])
        format.html { redirect_to user_libraries_url }
        format.json { head :ok }
      
      else
        format.html { render action: "edit" }
        format.json { render json: @user_library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_libraries/1
  # DELETE /user_libraries/1.json
  def destroy
    @user_library = UserLibrary.find(params[:id])
    @user_library.destroy

    respond_to do |format|
      format.html { redirect_to user_libraries_url }
      format.json { head :ok }
    end
  end


end

app/helpers/user_libraries_helper.rb
module UserLibrariesHelper

  #Método que comprueba antes de guardar una user library que la user library ya existe
  def save_userlibrary_check_repetition(p_userlibrary)

    userlibrary = UserLibrary.find_by_isbninfo_id_and_user_id(p_userlibrary.isbninfo_id, p_userlibrary.user_id)
    puts "La libreria es nueva en la base de datos? " + userlibrary.nil?.to_s
    if (userlibrary != nil)
      return userlibrary
    else
      p_userlibrary.save
      Activity.create_activity(
            current_user.id,
            Book2Drink::Application.config.activitytypebookaddedtolibrary,
            p_userlibrary.isbninfo_id)
      return p_userlibrary
    end
  end


end

app/views/user_libraries/_form.html.erb
<% @user_library = current_user.user_libraries.build %>

<%= form_for(@user_library) do |f| %>
  <% if @user_library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_library.errors.count, "error") %> prohibited this user_library from being saved:</h2>

      <ul>
        <% @user_library.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <li style="list-style:none;">

    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :isbninfo_id, :value => lIsbnInfoID %>
     <%= f.submit 'Añadir a mi librería', :id => 'botonAñadeLibro' %>
  </li>

<% end %>

app/views/user_libraries/_user_library.html.erb
<% isbninfo = Isbninfo.find(user_library.isbninfo_id) %>

<div class="libro">
  <div class="divFotoLibreriaUsuario">

    <% if isbninfo.photo.exists? then %>
      <%= image_tag isbninfo.photo.url(:thumb), :class=> 'thumbPhotoIsbnInfoSmall', :style => 'padding: 3px; float: left' %>
    <% else %>
      <%= image_tag "nophoto.jpg", :alt => 'isbninfo.title', :class=> 'thumbPhotoIsbnInfoSmall', :style => 'padding: 3px; float: left' %>
    <% end %>

  </div>


  <div style="float:right">

    <%= form_for(user_library) do |f| %>
      <% if user_library.favorite %>
        <%= f.hidden_field :favorite, :value => false %>
        <%= f.submit "Comment", :class => 'estilo_boton', :value => 'No Favorito'%>
      <% else %>
        <%= f.hidden_field :favorite, :value => true  %>
        <%= f.submit "Comment", :class => 'estilo_boton', :value => 'Favorito'%>
      <% end %>
    <% end %>

    <%= form_for(user_library) do |f| %>
      <% if user_library.wished %>
        <%= f.hidden_field :wished, :value => false %>
        <%= f.submit "Comment", :class => 'estilo_boton',:value => 'No Deseado'%>
      <% else %>
        <%= f.hidden_field :wished, :value => true %>
        <%= f.submit "Comment", :class => 'estilo_boton',:value => 'Deseado'%>
      <% end %>
    <% end %>

    <%= button_to "Eliminar de librería", user_library, :class => 'estilo_boton',:method=>:delete, :confirm => "Estás seguro?" %>
  </div>

  <div class="divLibreriaUsuarioInfoLibro">
    <span> <%= link_to isbninfo.title, isbninfo %> (<%= isbninfo.isbn13 %>)  </span>
    <p>de <%= isbninfo.author %></p> <br/>

    <div> <%= form_for(user_library) do |f| %>
        <%= f.select(:reading_status_book_id,
          ReadingStatusBook.all.collect {|p| [ p.reading_type, p.id ] },
          {},
          {:onChange => 'this.form.submit();', :id => 'flechaSelect' ,:class => 'estilo_boton'}
        )  %>
      <% end %>
    </div>
    <div class="favoritoLibreriaUsuario">
      <% if user_library.favorite %>
        <%= image_tag "favorite.png", :class => 'iconFavorite', :title => 'Libro favorito' %>
      <% end %>
    </div>
    <div class="deseadoLibreriaUsuario">
      <% if user_library.wished %>
        <%= image_tag "wished.png", :class => 'iconWished', :title => 'Libro deseado' %>
      <% end %>



    </div>
  </div>

</div>

app/views/user_libraries/edit.html.erb
<%= form_for(@user_library) do |f| %>
  <% if @user_library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_library.errors.count, "error") %> prohibited this user_library from being saved:</h2>

      <ul>
      <% @user_library.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	
	<div>
	favorite SI <%= radio_button(:user_library, :favorite, true) %>
			 NO <%= radio_button(:user_library, :favorite, false) %>
	</div>
	<div>
	wished 	SI <%= radio_button(:user_library, :wished, true) %>
			NO <%= radio_button(:user_library, :wished, false) %>
	</div>
	<div>isbninfo_id: <%= text_field(:user_library, :isbninfo_id, :class => 'round') %></div>
	<div>user_id: <%= text_field(:user_library, :user_id, :class => 'round') %></div>
	
	<%= select("user_library", 
		"reading_status_book_id", 
		ReadingStatusBook.all.collect {|p| [ p.reading_type, p.id ] }, 
		{:prompt => 'Estado de lectura'}) %> 
	
	
  	<%= f.submit %>
  
<% end %>





<%= link_to 'Show', @user_library %> |
<%= link_to 'Back', user_libraries_path %>

app/views/user_libraries/index.html.erb
<div class="divBorderLibreria">

  <div class="divLibreria">
    <div class="cabecera">

      <% user = current_user %>
      <span> <%= user.username %> tiene <%= @totalUserLibrary %> libros en su librería virtual</span>
      <div class="right">
        <%= link_to "Todos", 	user_user_libraries_path(current_user, :mode => "all") %> |
        <%= link_to "Favoritos", 	user_user_libraries_path(current_user, :mode => "favorites") %> |
        <%= link_to "Deseados", 	user_user_libraries_path(current_user, :mode => "wished") %>
      </div>
    </div>

    <div class="body">
      <%= render @user_libraries %>
      <%= paginate @user_libraries %>
    </div>



  </div>
  <div class="volver"> <%= render 'partials/link_back' %> </div>
</div>

app/views/user_libraries/new.html.erb
<h1>New user_library</h1>

<%= render 'form' %>

<%= link_to 'Back', user_libraries_path %>

app/views/user_libraries/public_userlibrary.html.erb
<div class="divBorderLibreria">

  <div class="divLibreria">
    <div class="cabecera">

      <span> <%= @user.username %></span> tiene <%= @totalUserLibrary %> libros en su librería pública
      <div class="right">
        <%= link_to "Todos", 	public_userlibrary_user_libraries_url(:user_id => @user.id, :mode => "all") %>|
        <%= link_to "Favoritos", 	public_userlibrary_user_libraries_url(:user_id => @user.id, :mode => "favorites") %> |
        <%= link_to "Deseados", 	public_userlibrary_user_libraries_url(:user_id => @user.id, :mode => "wished") %>
      </div>
    </div>

    <div class="body">
      <% @user_libraries.each do |user_library| %>

        <% isbninfo = user_library.isbninfo %>

        <div class="libro">
          <div class="divFotoLibreriaUsuario">

            <% if isbninfo.photo.exists? then %>
              <%= image_tag isbninfo.photo.url(:thumb), :class=> 'thumbPhotoIsbnInfoSmall', :style => 'padding: 3px; float: left' %>
            <% else %>
              <%= image_tag "nophoto.jpg", :alt => 'isbninfo.title', :class=> 'thumbPhotoIsbnInfoSmall', :style => 'padding: 3px; float: left' %>
            <% end %>

          </div>

          <div class="divLibreriaUsuarioInfoLibro">
            <span> <%= link_to isbninfo.title, isbninfo %> (<%= isbninfo.isbn13 %>) </span>
            <p>de <%= isbninfo.author %></p> <br/>
            <span>Estado de la lectura: <%= user_library.reading_status_book.reading_type   %> </span>
            <div class="favoritoLibreriaUsuario">
              <% if user_library.favorite %>
                <%= image_tag "favorite.png", :class => 'iconFavorite', :title => 'Libro favorito' %>
              <% end %>
            </div>
            <div class="deseadoLibreriaUsuario">
              <% if user_library.wished %>
                <%= image_tag "wished.png", :class => 'iconWished', :title => 'Libro deseado' %>
              <% end %>



            </div>
          </div>

        </div>





      <% end %>
      <%= paginate @user_libraries %>
    </div>



  </div>
  <div class="volver"> <%= render 'partials/link_back' %> </div>
</div>

app/views/user_libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Favorite:</b>
  <%= @user_library.favorite %>
</p>

<p>
  <b>Wished:</b>
  <%= @user_library.wished %>
</p>
<p>
  <b>Isbnid:</b>
  <%= @user_library.isbninfo_id %>
</p>  
<p>
  <b>estado de lectura:</b>
  <%= @user_library.reading_status_book_id %>
</p>  
    

<%= link_to 'Edit', edit_user_library_path(@user_library) %> |
<%= link_to 'Back', user_libraries_path %>