config/routes.rb
Book2Drink::Application.routes.draw do
  
  devise_for :users, :controllers => { :sessions => "devise/sessions",
                                       :omniauth_callbacks => "users/omniauth_callbacks" ,
                                       :registrations => "registration"
                                     }
  resources :users do
    resources :commentbooks
    resources :user_libraries
  end
  
  resources :events
  resources :user_libraries do
    collection do
      get 'public_userlibrary/:id', :action => 'public_userlibrary', :as => 'public_userlibrary'
    end
  end
  resources :city_types do
    resources :locations
  end
  resources :commentlocations
  resources :locations do
    resources :commentlocations
    resources :events
  end
  
  resources :commentbooks
  resources :isbninfos do 
    resources :commentbooks
    resources :user_libraries
    collection do
      get 'indexsearchbooks'
      post 'addtobooks'
    end
  end
  match "aftersignin_step1" => "registrati"

  get "admin/users"
  get "admin/locations"
  get "admin/isbninfos"
  get "admin/console"
  get "main/index"

  match "tour" => "main#tour"

  root :to => 'main#index'

end

app/models/commentbook.rb
class Commentbook < ActiveRecord::Base  
  belongs_to :isbninfo
  belongs_to :user

  
  
end

app/controllers/commentbooks_controller.rb
class CommentbooksController < ApplicationController
  protect_from_forgery
  before_filter :verify_admin, :only => [:index, :edit, :show, :update]

  # GET /commentbooks
  # GET /commentbooks.json
  def index
    
    @isbninfo = Isbninfo.find(params[:isbninfo_id])
    @commentbooks = @isbninfo.commentbooks
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @commentbooks  }
    end
  end

  # GET /commentbooks/1
  # GET /commentbooks/1.json
  def show
    @commentbook = Commentbook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @commentbook }
    end
  end

  # GET /commentbooks/new
  # GET /commentbooks/new.json
  def new
              #@isbninfo = Isbninfo.find(params[:isbninfo_id])
              #@commentbook = @isbninfo.commentbooks.build
              #@commentbook.user = current_user
  end

  # GET /commentbooks/1/edit
  def edit
    @commentbook = Commentbook.find(params[:id])
  end

  
  #def create
  #    @isbninfo = Isbninfo.find(params[:isbninfo_id])
  #    @comment = @isbninfo.commentbooks.create(params[:comment])
  #    
  #    format.html { redirect_to isbninfo_url(@isbninfo), notice: 'Has creado el comentario con exito.' }
  #end

  # POST /commentbooks
  # POST /commentbooks.json
  def create
    @commentbook = Commentbook.new(params[:commentbook])
    @isbninfo = Isbninfo.find(@commentbook.isbninfo_id)
    respond_to do |format|
      if @commentbook.save
        Activity.create_activity(
          current_user.id,
          Book2Drink::Application.config.activitytypecommentbook,
          @commentbook.id)
        format.html { redirect_to @isbninfo, notice: 'Gracias por comentar el bar.' }
        format.json { render json: @commentbook, status: :created, location: @commentbook }
      else
        format.html { render action: "new" }
        format.json { render json: @commentbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /commentbooks/1
  # PUT /commentbooks/1.json
  def update
    @commentbook = Commentbook.find(params[:id])

    respond_to do |format|
      if @commentbook.update_attributes(params[:commentbook])
        format.html { redirect_to @commentbook, notice: 'Commentbook was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @commentbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commentbooks/1
  # DELETE /commentbooks/1.json
  def destroy
    @commentbook = Commentbook.find(params[:id])
    @commentbook.destroy

    respond_to do |format|
      format.html { redirect_to commentbooks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/commentbooks_helper.rb
module CommentbooksHelper
end

app/views/commentbooks/_commentbook.html.erb
<div class="section">
  <%
  if commentbook.user_id
    @user = User.find(commentbook.user_id)
  %>
    <%= link_to @user.username , user_path(@user) %>

  <% else %>
                                  Usuario anónimo
  <% end %>

 		- <%= commentbook.created_at %>: <%= commentbook.commenttext %>	
</div>

app/views/commentbooks/_form.html.erb
<%= form_for(@commentbook) do |f| %>
  <% if @commentbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commentbook.errors.count, "error") %> prohibited this commentbook from being saved:</h2>

      <ul>
        <% @commentbook.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <br/>
  <div class="etiquetas" style="color: inherit;font-weight: bold; opacity:0.7;"> Deja tu comentario sobre: <%= @isbninfo.title %> </div>
  <%= text_area(:commentbook, :commenttext, :class => 'boxOpinionLibro') %>

  <%= f.hidden_field :isbninfo_id, :value => @commentbook.isbninfo_id %>
  <%= f.hidden_field :user_id, :value => @commentbook.user_id %>

  <%= f.submit "Envía", :class => 'actions' %>


<% end %>

app/views/commentbooks/edit.html.erb
<h1>Editing commentbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @commentbook %> |
<%= link_to 'Back', commentbooks_path %>

app/views/commentbooks/index.html.erb
<h1>Listing commentbooks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commentbooks.each do |commentbook| %>

<tr>
    <td>Comentario: <%= commentbook.commenttext %></td>
  </tr>
  <tr>
    <td><%= link_to 'Destroy', commentbook, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to "¿Quieres comentar el libro?", new_isbninfo_commentbook_path(@isbninfo) %>

<br/>

app/views/commentbooks/new.html.erb
<h1>Nuevo comentario del libro <%= @isbninfo.title %></h1>
<%= render 'form' %>

<%= link_to 'Volver', request.referer %>

app/views/commentbooks/show.html.erb
<p id="notice"><%= notice %></p>

Isbn del libro: <%= @commentbook.isbninfo_id  %>
Comentario: <%=@commentbook.commenttext %>

<%= link_to 'Edit', edit_commentbook_path(@commentbook) %> |
<%= link_to 'Back', commentbooks_path %>